name: neotest Workflow
on:
  push:
    branches:
      - master
  pull_request: ~
  workflow_dispatch: {}
jobs:
  style:
    name: style
    if: ${{ github.repository == 'nvim-neotest/neotest' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ tests/

  tests:
    name: tests
    if: ${{ github.repository == 'nvim-neotest/neotest' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        nvim_version: ['v0.11.6', 'nightly']
    steps:
      - uses: actions/checkout@v5
      - uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.nvim_version }}

  release:
    name: release
    if: ${{ (github.repository == 'nvim-neotest/neotest' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
    needs:
      - style
      - tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  luarocks-upload:
    if: ${{ github.repository == 'nvim-neotest/neotest' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git fetch --tags; git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          dependencies: |
            nvim-nio
